import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import { StyledComponentsRegistry, ThemeProvider } from "styles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='flex max-w-[1440px] min-h-screen mx-auto flex-col px-3 lg:px-6 '>
          <header>header</header>
          <StyledComponentsRegistry>
            <ThemeProvider>{children}</ThemeProvider>
          </StyledComponentsRegistry>
          <footer className='mt-auto'>footer</footer>
        </main>
      </body>
    </html>
  );
}
